//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.12 at 09:59:43 AM CET 
//


package org.aaaarch.tvs.token;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for AuthzTokenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthzTokenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.aaauthreach.org/ns/AAA}TokenValue" minOccurs="0"/>
 *         &lt;element name="Conditions" type="{http://www.aaauthreach.org/ns/AAA}ConditionsType" minOccurs="0"/>
 *         &lt;element name="Decision" type="{http://www.aaauthreach.org/ns/AAA}DecisionType" minOccurs="0"/>
 *         &lt;element name="Domains" type="{http://www.aaauthreach.org/ns/AAA}DomainsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tokentype">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="access-token"/>
 *             &lt;enumeration value="pilot-type1"/>
 *             &lt;enumeration value="pilot-type2"/>
 *             &lt;enumeration value="pilot-type3"/>
 *             &lt;enumeration value="pilot-type4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TokenID" use="required" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *       &lt;attribute name="SessionID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Issuer" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthzTokenType", propOrder = {
    "tokenValue",
    "conditions",
    "decision",
    "domains"
})
public class AuthzTokenType {

    @XmlElement(name = "TokenValue")
    protected String tokenValue;
    @XmlElement(name = "Conditions")
    protected ConditionsType conditions;
    @XmlElement(name = "Decision")
    protected DecisionType decision;
    @XmlElement(name = "Domains")
    protected DomainsType domains;
    @XmlAttribute
    protected String tokentype;
    @XmlAttribute(name = "TokenID", required = true)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] tokenID;
    @XmlAttribute(name = "SessionID", required = true)
    protected String sessionID;
    @XmlAttribute(name = "Issuer")
    @XmlSchemaType(name = "anyURI")
    protected String issuer;

    /**
     * Gets the value of the tokenValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenValue() {
        return tokenValue;
    }

    /**
     * Sets the value of the tokenValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenValue(String value) {
        this.tokenValue = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionsType }
     *     
     */
    public ConditionsType getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionsType }
     *     
     */
    public void setConditions(ConditionsType value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the decision property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionType }
     *     
     */
    public DecisionType getDecision() {
        return decision;
    }

    /**
     * Sets the value of the decision property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionType }
     *     
     */
    public void setDecision(DecisionType value) {
        this.decision = value;
    }

    /**
     * Gets the value of the domains property.
     * 
     * @return
     *     possible object is
     *     {@link DomainsType }
     *     
     */
    public DomainsType getDomains() {
        return domains;
    }

    /**
     * Sets the value of the domains property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainsType }
     *     
     */
    public void setDomains(DomainsType value) {
        this.domains = value;
    }

    /**
     * Gets the value of the tokentype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokentype() {
        return tokentype;
    }

    /**
     * Sets the value of the tokentype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokentype(String value) {
        this.tokentype = value;
    }

    /**
     * Gets the value of the tokenID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getTokenID() {
        return tokenID;
    }

    /**
     * Sets the value of the tokenID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenID(byte[] value) {
        this.tokenID = ((byte[]) value);
    }

    /**
     * Gets the value of the sessionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionID() {
        return sessionID;
    }

    /**
     * Sets the value of the sessionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionID(String value) {
        this.sessionID = value;
    }

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuer(String value) {
        this.issuer = value;
    }

}
