//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.12 at 09:59:43 AM CET 
//


package org.aaaarch.tvs.token;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DomainType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuthzToken" type="{http://www.aaauthreach.org/ns/AAA}AuthzTokenType" minOccurs="0"/>
 *         &lt;element name="KeyInfo" type="{http://www.aaauthreach.org/ns/AAA}KeyInfoType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="domainId" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainType", propOrder = {
    "authzToken",
    "keyInfo"
})
public class DomainType {

    @XmlElement(name = "AuthzToken")
    protected AuthzTokenType authzToken;
    @XmlElement(name = "KeyInfo", required = true)
    protected List<KeyInfoType> keyInfo;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String domainId;

    /**
     * Gets the value of the authzToken property.
     * 
     * @return
     *     possible object is
     *     {@link AuthzTokenType }
     *     
     */
    public AuthzTokenType getAuthzToken() {
        return authzToken;
    }

    /**
     * Sets the value of the authzToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthzTokenType }
     *     
     */
    public void setAuthzToken(AuthzTokenType value) {
        this.authzToken = value;
    }

    /**
     * Gets the value of the keyInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyInfoType }
     * 
     * 
     */
    public List<KeyInfoType> getKeyInfo() {
        if (keyInfo == null) {
            keyInfo = new ArrayList<KeyInfoType>();
        }
        return this.keyInfo;
    }

    /**
     * Gets the value of the domainId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * Sets the value of the domainId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainId(String value) {
        this.domainId = value;
    }

}
