//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.12 at 09:59:43 AM CET 
//


package org.aaaarch.tvs.token;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.aaauthreach.ns.aaa package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TokenValue_QNAME = new QName("http://www.aaauthreach.org/ns/AAA", "TokenValue");
    private final static QName _AuthzToken_QNAME = new QName("http://www.aaauthreach.org/ns/AAA", "AuthzToken");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.aaauthreach.ns.aaa
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthzTokenType }
     * 
     */
    public AuthzTokenType createAuthzTokenType() {
        return new AuthzTokenType();
    }

    /**
     * Create an instance of {@link ObligationType }
     * 
     */
    public ObligationType createObligationType() {
        return new ObligationType();
    }

    /**
     * Create an instance of {@link ObligationsType }
     * 
     */
    public ObligationsType createObligationsType() {
        return new ObligationsType();
    }

    /**
     * Create an instance of {@link KeyInfoType }
     * 
     */
    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }

    /**
     * Create an instance of {@link DomainType }
     * 
     */
    public DomainType createDomainType() {
        return new DomainType();
    }

    /**
     * Create an instance of {@link DecisionType }
     * 
     */
    public DecisionType createDecisionType() {
        return new DecisionType();
    }

    /**
     * Create an instance of {@link ConditionsType }
     * 
     */
    public ConditionsType createConditionsType() {
        return new ConditionsType();
    }

    /**
     * Create an instance of {@link DomainsType }
     * 
     */
    public DomainsType createDomainsType() {
        return new DomainsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.aaauthreach.org/ns/AAA", name = "TokenValue")
    public JAXBElement<String> createTokenValue(String value) {
        return new JAXBElement<String>(_TokenValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthzTokenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.aaauthreach.org/ns/AAA", name = "AuthzToken")
    public JAXBElement<AuthzTokenType> createAuthzToken(AuthzTokenType value) {
        return new JAXBElement<AuthzTokenType>(_AuthzToken_QNAME, AuthzTokenType.class, null, value);
    }

}
